Algoritmo "Exercicio"

Var

   produto1: caractere
   produto2: caractere
   genero: caractere
   preco1: real
   preco2: real
   idade: inteiro
   codigo: inteiro
   

Inicio

      produto1 <- "computador"
      produto2 <- "TV"
      genero <- "F"
      preco1 <- 2100.5
      preco2 <- 1830.0
      idade <- 30
      codigo <- 5291
      
      escreval("O produto ", produto1," custa R$", preco1)
      escreval("O produto ", produto2," custa R$", preco2)
      escreval("Codigo ", codigo)
      escreva("Dados da pessoa: genero ", genero, " e idade", idade)

Fimalgoritmo