Algoritmo "ExercicioSoma"

Var
     x, y : real
     soma1, soma2, soma3, soma4 : real

Inicio

      escreva("Digite o valor de X: ")
      leia(x)
      escreva("Digite o valor de Y: ")
      leia(y)
      
      soma1 <- x + y
      soma2 <- x - y
      soma3 <- x * y
      soma4 <- x / y
      
      escreval("A soma da adição eh: ", soma1:4:2)
      escreval("A soma da subtração eh: ", soma2:4:2)
      escreval("A soma da multiplicação eh: ", soma3:4:2)
      escreval("A soma da divisão eh: ", soma4:4:2)
      

Fimalgoritmo