Algoritmo "Medidas"

Var

   a, b, c, quadradro, triangulo, trapezio : real
Inicio

      escreva("Digite a medida A: ")
      leia(a)
      escreva("Digite a medida B: ")
      leia(b)
      escreva("Digite a medida C: ")
      leia(c)
      
      quadradro <- a * a
      triangulo <- a * b / 2
      trapezio <- (a + b) / 2 * c) // trapezio <- (a + b) * c / 2
      
      escreval("-------------------------------")
      escreval("AREA DO QUADRADRO = ", quadradro:5:4)
      escreval("AREA DO TRIANGULO = ", triangulo:5:4)
      escreval("AREA DO TRAPEZIO = ", trapezio:5:4)
      
      

Fimalgoritmo